// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ToEtLJDCRuYdsP87W2JnNkoc-7jHruY',
    appId: '1:608745590680:web:2f68dceac9d67ed8aea5ed',
    messagingSenderId: '608745590680',
    projectId: 'ecommerce-app-8a48c',
    authDomain: 'ecommerce-app-8a48c.firebaseapp.com',
    storageBucket: 'ecommerce-app-8a48c.appspot.com',
    measurementId: 'G-8GNVS15DVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFhL-lNcZPNBJe0-sWo2paihIR8miPGTA',
    appId: '1:608745590680:android:06ae6fa42c6ff082aea5ed',
    messagingSenderId: '608745590680',
    projectId: 'ecommerce-app-8a48c',
    storageBucket: 'ecommerce-app-8a48c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5jt6HyrpR8iCv9cnIDX1cziicip-SP5Q',
    appId: '1:608745590680:ios:aece16913dc88cd3aea5ed',
    messagingSenderId: '608745590680',
    projectId: 'ecommerce-app-8a48c',
    storageBucket: 'ecommerce-app-8a48c.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5jt6HyrpR8iCv9cnIDX1cziicip-SP5Q',
    appId: '1:608745590680:ios:aece16913dc88cd3aea5ed',
    messagingSenderId: '608745590680',
    projectId: 'ecommerce-app-8a48c',
    storageBucket: 'ecommerce-app-8a48c.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8ToEtLJDCRuYdsP87W2JnNkoc-7jHruY',
    appId: '1:608745590680:web:fad6e577e520dc28aea5ed',
    messagingSenderId: '608745590680',
    projectId: 'ecommerce-app-8a48c',
    authDomain: 'ecommerce-app-8a48c.firebaseapp.com',
    storageBucket: 'ecommerce-app-8a48c.appspot.com',
    measurementId: 'G-7VV4SQGQ93',
  );
}
